# Generated by Django 2.2.10 on 2020-03-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('confirm_password', models.CharField(max_length=10)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField()),
                ('Select_Preferred_Location', models.CharField(choices=[('mumbai', 'Mumbai'), ('pune ', 'pune'), ('delhi', 'Delhi'), ('agra', 'Agra'), ('goa', 'Goa')], max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registrations', to='registration.Registrations')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preferences', models.CharField(choices=[('Food & Dinings', 'Food & Dinings'), ('Travel & Outdoor ', 'Travel & Outdoor'), ('Events', 'Events'), ('Nightlife', 'Nightlife'), ('Gifts & Shopping', 'Gifts & Shopping'), ('Deals & Offers', 'Deals & Offers')], max_length=1000)),
                ('images', models.ImageField(default='', upload_to='registrations/images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='registration.Profile')),
            ],
        ),
    ]
