# Generated by Django 2.2.10 on 2020-03-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'user already exist.'}, max_length=50, unique=True),
        ),
    ]
