# Generated by Django 2.2.10 on 2020-03-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200320_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='email',
            field=models.EmailField(default='', error_messages={'unique': 'This email Id already.'}, max_length=254, unique=True),
        ),
    ]
