# Generated by Django 2.2.10 on 2020-03-21 13:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200320_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='opt',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='phone_no',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
