# Generated by Django 2.2.10 on 2020-03-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200321_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='phone_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
