# Generated by Django 2.2.10 on 2020-03-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200321_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrations',
            old_name='opt',
            new_name='OTP',
        ),
    ]
