# Generated by Django 2.2.10 on 2020-03-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpverification',
            old_name='opt',
            new_name='OTP',
        ),
    ]
